name: TruffleHog Scan

on:
  push:
    branches:
      - "main"

jobs:
  secret-scan:
    runs-on: self-hosted  # or 'ubuntu-latest' for GitHub-hosted runners

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To ensure the full history is fetched, needed for scanning

      - name: Run TruffleHog Scan on the Current Repository
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          trufflehog --regex --entropy=True --json $REPO_URL | jq
