name: TruffleHog Scan

on:
  push:
    branches:
      - "main"

jobs:
  secret-scan:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies (jq, curl, git)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl git

      - name: Run TruffleHog Scan
        run: |
          trufflehog --regex --entropy=True --json https://github.com/your-username/your-repo.git | jq
