name: TruffleHog Scan

on:
  push:
    branches: ["main"]

jobs:
  secret-scan:
    runs-on: self-hosted  

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run TruffleHog Scan on the Current Repository
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          trufflehog --regex --entropy=True --json $REPO_URL | jq
